
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 23 23:38:05 CET 2010
//----------------------------------------------------

package mk262968.javalette.ast;

public interface JavaletteConstants {
  /* terminals */
  public static final int PLUS=1;
  public static final int MINUS=2;
  public static final int MULT=3;
  public static final int DIV=4;
  public static final int MOD=5;
}
